/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ASSET.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/ASSET.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface2.geometry} material={materials.MAT} scale={18}/>
    </group>
  )
}

useGLTF.preload('/ASSET.gltf')
